# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bp < Formula
  desc "Skip writing repetitive boilerplate code"
  homepage "https://github.com/ukhirani/boilerplate"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.2/bp_darwin_amd64.tar.gz"
    sha256 "36f2de62178f5992604dd45cbf4f502ac624212a74639f6d204b9cfa34f3df40"

    def install
      bin.install "bp"
    end
  end
  on_arm do
    url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.2/bp_darwin_arm64.tar.gz"
    sha256 "4ba201997ee453a0874712a617817566e83eaf3eb8c10b0350d9cb1f5474b17f"

    def install
      bin.install "bp"
    end
  end
end
