# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bp < Formula
  desc "Skip writing repetitive boilerplate code"
  homepage "https://github.com/ukhirani/boilerplate"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.4/bp_darwin_amd64.tar.gz"
      sha256 "3990f08707f3e0bb2f136d14e638d7b6fdad0fc9ac1c6586035edf531905c92e"

      def install
        bin.install "bp"
      end
    end
    on_arm do
      url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.4/bp_darwin_arm64.tar.gz"
      sha256 "bba1a5b1e1d6d40832672759efd5cfab4167568e7f6cf0821e0615bcf5a66da9"

      def install
        bin.install "bp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.4/bp_linux_amd64.tar.gz"
        sha256 "77e6fecf89bc299f191ec057f7d04dd2e6767b535be78c2b0188a454260a8287"

        def install
          bin.install "bp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.4/bp_linux_arm64.tar.gz"
        sha256 "b78055fc8bd0f18b90dd1cc1785dd29c8b96a027b20e5626efef32f23c076563"

        def install
          bin.install "bp"
        end
      end
    end
  end
end
