# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bp < Formula
  desc "Skip writing repetitive boilerplate code"
  homepage "https://github.com/ukhirani/boilerplate"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.7/bp_darwin_amd64.tar.gz"
      sha256 "5fc8459409429ad6ab2ad99d3a25fc0cbc8671ee918127ce969cc0254d4963e4"

      def install
        bin.install "bp"
      end
    end
    on_arm do
      url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.7/bp_darwin_arm64.tar.gz"
      sha256 "13880fb659e5bb3a95f990699e85811fcc82e1ad7cfd56361d1449f964b61313"

      def install
        bin.install "bp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.7/bp_linux_amd64.tar.gz"
        sha256 "1ea62393c71a7984dd47a02fcc52179d159d38d02d891292d37f0a91175d452c"

        def install
          bin.install "bp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.7/bp_linux_arm64.tar.gz"
        sha256 "4728203c01111bb3219191406272ee8a0c74d70fd4c9b9a8603dd0c732beb379"

        def install
          bin.install "bp"
        end
      end
    end
  end
end
