# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bp < Formula
  desc "Skip writing repetitive boilerplate code"
  homepage "https://github.com/ukhirani/boilerplate"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ukhirani/boilerplate/releases/download/v1.0.1/bp_darwin_amd64.tar.gz"
      sha256 "67c55fa6511240d9134d8864dcb0ba461ec4347d2376ddb9c8f643e9c2bd9958"

      def install
        bin.install "bp"
      end
    end
    on_arm do
      url "https://github.com/ukhirani/boilerplate/releases/download/v1.0.1/bp_darwin_arm64.tar.gz"
      sha256 "fc987b4fc711e169cf5931922f355febd87aeef6bc504601165e9a6f30ba94dd"

      def install
        bin.install "bp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ukhirani/boilerplate/releases/download/v1.0.1/bp_linux_amd64.tar.gz"
        sha256 "fd50980468b267cf1c34d0a882d614232dc476464784797d8c568f2856e64bb9"

        def install
          bin.install "bp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ukhirani/boilerplate/releases/download/v1.0.1/bp_linux_arm64.tar.gz"
        sha256 "d32a495cc383e27148220d0bb115d2261ee19f592b68b7b0366437428d883921"

        def install
          bin.install "bp"
        end
      end
    end
  end
end
