# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bp < Formula
  desc "Skip writing repetitive boilerplate code"
  homepage "https://github.com/ukhirani/boilerplate"
  version "0.1.84"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.84/bp_darwin_amd64.tar.gz"
      sha256 "3ef70d7a5aa4e2968d1a1a643dfb2ccc7817c85bb8eb2e3ab268f9c664bf35c5"

      def install
        bin.install "bp"
      end
    end
    on_arm do
      url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.84/bp_darwin_arm64.tar.gz"
      sha256 "497ac90e408ccc26b99955ff495dfcde6200ce034e4a9e71d56ce40fa72a03f8"

      def install
        bin.install "bp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.84/bp_linux_amd64.tar.gz"
        sha256 "c5fc7b79b7938e45f87185726e5bece2c07a73c4fc9263aad1ea607ef1313305"

        def install
          bin.install "bp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ukhirani/boilerplate/releases/download/v0.1.84/bp_linux_arm64.tar.gz"
        sha256 "49a6949d253d50e9ac540b929021f7718e1fba8852af525f179bf4715bda5434"

        def install
          bin.install "bp"
        end
      end
    end
  end
end
